apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-pod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart-role
  # namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-restart-binding
  # namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-restart-role
subjects:
- kind: ServiceAccount
  name: kubectl-pod
  # namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
spec:
  serviceAccountName: kubectl-pod
  containers:
  - name: kubectl-container
    image: bitnami/kubectl
    command: ["sleep"]
    args: ["infinity"]
