apiVersion: v1
kind: Service
metadata:
  name: exatorrent-service
  labels:
    app: exatorrent
spec:
  selector:
    app: exatorrent
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exatorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exatorrent
  template:
    metadata:
      labels:
        app: exatorrent
    spec:
      containers:
        - name: exatorrent
          image: ghcr.io/varbhat/exatorrent:latest
          ports:
            - containerPort: 5000
              name: exatorrent
              protocol: TCP
            - containerPort: 42069
              name: exatorrent2
              protocol: TCP
              # this create /exa/exadir with link srv ?
              # should be correct?
          volumeMounts:
            - mountPath: /exa
              name: exatorrent-volume
      volumes:
        - name: exatorrent-volume
          persistentVolumeClaim:
            claimName: main-pvc
