#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: file-pvc
#  namespace: default
#spec:
#  storageClassName: rook-cephfs
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser-service
  labels:
    app: filebrowser
spec:
  selector:
    app: filebrowser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:s6
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /srv
          name: filebrowser-volume
      volumes:
      - name: filebrowser-volume
        persistentVolumeClaim:
          claimName: main-pvc
