apiVersion: v1
kind: Namespace
metadata:
  name: sonar
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
  namespace: sonar
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/pv0002/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-pvc
  namespace: sonar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-config
  namespace: sonar
  labels:
    app: sonar
data:
  # Database configuration for sonarqube
  # SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar_db"
  # SONARQUBE_JDBC_USERNAME: "sonar_user"
  # SONARQUBE_JDBC_PASSWORD: "S0N4RQUB3"

  # Database configuration for bitnami/sonarqube
  # https://github.com/bitnami/containers/tree/main/bitnami/sonarqube#configuration
  SONARQUBE_DATABASE_USER: "sonar_user"
  SONARQUBE_DATABASE_PASSWORD: "S0N4RQUB3"
  SONARQUBE_DATABASE_HOST: "postgres"
  SONARQUBE_DATABASE_NAME: "sonar_db"
  JAVA_OPTS: "-Duser.timezone=Asia/Jakarta -Xmx2048m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
  namespace: sonar
  labels:
    app: sonar
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      initContainers:
      - name: init
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
      containers:
      - name: sonarqube
        # image: sonarqube:10.2.0-community
        # image: bitnami/sonarqube:10.3.0
        image: bitnami/sonarqube:10.4.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: sonar-config
        volumeMounts:
        - name: app-pvc
          mountPath: "/opt/sonarqube/data/"
          subPath: data
        - name: app-pvc
          mountPath: "/opt/sonarqube/extensions/"
          subPath: extensions
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "2048Mi"
      volumes:
      - name: app-pvc
        persistentVolumeClaim:
          claimName: sonar-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-svc
  namespace: sonar
  labels:
    app: sonar
spec:
  ports:
  - port: 9000
    targetPort: 9000
    name: sonar
  selector:
    app: sonar
---
