kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: listmonk
  namespace: listmonk
spec:
  interval: 10s
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - https://eevans.co/subscription/form
---
