apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: listmonk
  namespace: listmonk
spec:
  groups:
    - name: listmonk.listmonk
      rules:
        - alert: ListmonkDown
          annotations:
            summary: Listmonk blog is unavailable
          expr: probe_success{job="probe/listmonk/listmonk",namespace="listmonk"} != 1
          for: 30s
          labels:
            severity: critical
