apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: hotchoc
  name: hotchoc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hotchoc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/hotchoc-default: "true"
        io.kompose.service: hotchoc
    spec:
      containers:
        - image: hotchoc
          name: hotchoc
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
