---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          # base image: https://hub.docker.com/r/cloudflare/cloudflared
          image: cloudflare/cloudflared:2023.8.0-arm64
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/config
              readOnly: true
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
            - name: cert
              mountPath: /etc/cloudflared
              readOnly: true
      volumes:
        - name: creds
          secret:
            secretName: tunnel-credentials
        - name: config
          configMap:
            name: cloudflared
            items:
              - key: config.yaml
                path: config.yaml
        - name: cert
          secret:
            secretName: cloudflared-cert
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
data:
  # <service-name>.<namespace>.svc.cluster.local
  config.yaml: |
    tunnel: ktunnel
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: tunnel.<URL>.io
      service: http://nginx.default.svc.cluster.local:80
    - service: http_status:404
