apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "echo-api.fullname" . }}-health-check
  labels:
    {{- include "echo-api.labels" . | nindent 4 }}
spec:
  args:
    - name: service-name
    - name: namespace
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: port
      value: "{{ .Values.service.port }}"
  metrics:
    {{- range .Values.rollout.analysis.metrics }}
    - name: {{ .name }}
      interval: {{ .interval }}
      {{- if .successCondition }}
      successCondition: {{ .successCondition }}
      {{- end }}
      {{- if .failureCondition }}
      failureCondition: {{ .failureCondition }}
      {{- end }}
      {{- if .failureLimit }}
      failureLimit: {{ .failureLimit }}
      {{- end }}
      {{- if .count }}
      count: {{ .count }}
      {{- end }}
      provider:
        {{- toYaml .provider | nindent 8 }}
    {{- end }}
