apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "echo-api.fullname" . }}
  labels:
    {{- include "echo-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.rollout.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "echo-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "echo-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "echo-api.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
  strategy:
    blueGreen:
      activeService: {{ include "echo-api.fullname" . }}-active
      previewService: {{ include "echo-api.fullname" . }}-preview
      autoPromotionEnabled: {{ .Values.rollout.strategy.blueGreen.autoPromotionEnabled }}
      {{- if .Values.rollout.strategy.blueGreen.autoPromotionSeconds }}
      autoPromotionSeconds: {{ .Values.rollout.strategy.blueGreen.autoPromotionSeconds }}
      {{- end }}
      scaleDownDelaySeconds: {{ .Values.rollout.strategy.blueGreen.scaleDownDelaySeconds }}
      {{- if .Values.rollout.strategy.blueGreen.previewReplicaCount }}
      previewReplicaCount: {{ .Values.rollout.strategy.blueGreen.previewReplicaCount }}
      {{- end }}
      {{- if .Values.rollout.strategy.blueGreen.postPromotionAnalysis }}
      postPromotionAnalysis:
        templates:
          - templateName: {{ include "echo-api.fullname" . }}-health-check
        args:
          - name: service-name
            value: {{ include "echo-api.fullname" . }}-active
          - name: namespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      prePromotionAnalysis:
        templates:
          - templateName: {{ include "echo-api.fullname" . }}-health-check
        args:
          - name: service-name
            value: {{ include "echo-api.fullname" . }}-preview
          - name: namespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      {{- end }}
