# Active Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-api.fullname" . }}-active
  labels:
    {{- include "echo-api.labels" . | nindent 4 }}
    role: active
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "echo-api.selectorLabels" . | nindent 4 }}
---
# Preview Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-api.fullname" . }}-preview
  labels:
    {{- include "echo-api.labels" . | nindent 4 }}
    role: preview
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "echo-api.selectorLabels" . | nindent 4 }}
---
# Main Service that can be used to access the active deployment
apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-api.fullname" . }}
  labels:
    {{- include "echo-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "echo-api.selectorLabels" . | nindent 4 }}
