version: '3.5'

services:
    cobalt-api:
        image: ghcr.io/imputnet/cobalt:7
        restart: unless-stopped
        container_name: cobalt-api
        init: true
        ports:
            - 9000:9000/tcp
        environment:
            API_URL: "http://localhost:9000"
            API_NAME: "eu-nl"
        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

    cobalt-web:
        image: ghcr.io/imputnet/cobalt:7
        restart: unless-stopped
        container_name: cobalt-web
        init: true
        ports:
            - 9001:9001/tcp
        environment:
            WEB_URL: "http://localhost:9001"
            API_URL: "http://localhost:9000"
        labels:
            - com.centurylinklabs.watchtower.scope=cobalt

    watchtower:
        image: ghcr.io/containrrr/watchtower
        restart: unless-stopped
        command: --cleanup --scope cobalt --interval 900 --include-restarting
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
