apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api-server
  template:
    metadata:
      labels:
        app: go-api-server
    spec:
      containers:
      - name: go-api-server
        image: loneexile/stress-multi:latest
        ports:
        - containerPort: 8282
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /fibonacci?n=1
            port: 8282
          initialDelaySeconds: 5
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: go-api-server
spec:
  selector:
    app: go-api-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8282
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-api-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-api-server
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
