apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  labels:
    app: postgres
data:
  POSTGRESQL_USERNAME: affine
  POSTGRESQL_DATABASE: affine
  POSTGRESQL_PASSWORD: affine
---
apiVersion: v1
kind: Service
metadata:
  name: affine-postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: affine-postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 2000 
      containers:
      - name: postgress
        image: bitnami/postgresql
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres
        volumeMounts:
        - name: postgres
          mountPath: /bitnami/postgresql
          subPath: home/affine/postgresql
        # env:
        # - name: ALLOW_EMPTY_PASSWORD
        #   value: "yes"
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: nfs-pvc-worker-1
