apiVersion: v1
kind: Service
metadata:
  name: affine-redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: affine-redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis
          mountPath: /data
          subPath: home/affine/redis
      volumes:
      - name: redis
        persistentVolumeClaim:
          claimName: nfs-pvc-worker-1
