namespace: nfs-provisioner-worker-1
resources:
- namespace.yaml
# - github.com/kubernetes-sigs/nfs-subdir-external-provisioner//deploy
- ./deploy
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: patch_nfs_details.yaml
