apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner-worker-1
            - name: NFS_SERVER
              value: 192.168.1.21
            - name: NFS_PATH
              value: /mnt/nvme0n1
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.1.21
            path: /mnt/nvme0n1
