apiVersion: v1
kind: Service
metadata:
  name: audiobookshelf-service
  labels:
    app: audiobookshelf
spec:
  selector:
    app: audiobookshelf
  ports:
    - protocol: TCP
      port: 13378
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:latest
          ports:
            - containerPort: 80
              name: audiobookshelf
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: audiobookshelf-volume-nfs
              subPath: config/audiobookshelf/config
            - mountPath: /metadata
              name: audiobookshelf-volume-nfs
              subPath: config/audiobookshelf/metadata
            
            - mountPath: /podcasts
              name: audiobookshelf-volume-nfs
              subPath: home/audiobookshelf/audiobooks
            - mountPath: /audiobooks
              name: audiobookshelf-volume-nfs
              subPath: home/audiobookshelf/podcasts
          env:
            - name: TZ
              value: "Asia/Bangkok"

      volumes:
        - name: audiobookshelf-volume-nfs
          persistentVolumeClaim:
            # claimName: bob-nfs-pvc
            claimName: nfs-pvc-worker-1
