apiVersion: v1
kind: Service
metadata:
  name: dashy-service
  labels:
    app: dashy
spec:
  selector:
    app: dashy
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
        - name: dashy
          image: lissy93/dashy:latest
          ports:
            - containerPort: 8080
              name: dashy-1
              protocol: TCP
          volumeMounts:
            - mountPath: /app/user-data
              name: dashy-volume-nfs
              subPath: config/dashy/user-data
            # - name: config
            #   mountPath: /app/public/conf.yml
            #   subPath: config/dashy/conf.yml


      volumes:
        - name: dashy-volume-nfs
          persistentVolumeClaim:
            # claimName: bob-nfs-pvc
            claimName: nfs-pvc-worker-1
        # - name: config
        #   configMap:
        #     name: dashy
        #     items:
        #       - key: conf.yml
        #         path: conf.yml

---
# apiVersion: v1
# kind: dashy
# metadata:
#   name: dashy
#   namespace: dashy
# data:
#   conf.yml: |
#     pageInfo:
#       title: Home Lab
#
