apiVersion: v1
kind: Service
metadata:
  name: filebrowser-service
  labels:
    app: filebrowser
spec:
  selector:
    app: filebrowser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:s6
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /database
              name: filebrowser-volume-nfs
              subPath: config/filebrowser/database
            - mountPath: /srv
              name: filebrowser-volume-nfs
              # subPath: srv
      volumes:
        - name: filebrowser-volume-nfs
          persistentVolumeClaim:
            claimName: bob-nfs-pvc
