apiVersion: v1
kind: Service
metadata:
  name: filebrowser-service-worker-1
  labels:
    app: filebrowser-worker-1
spec:
  selector:
    app: filebrowser-worker-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser-worker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser-worker-1
  template:
    metadata:
      labels:
        app: filebrowser-worker-1
    spec:
      containers:
        - name: filebrowser-worker-1
          image: filebrowser/filebrowser:s6
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /database
              name: filebrowser-volume-nfs
              subPath: config/filebrowser1/database
            - mountPath: /srv
              name: filebrowser-volume-nfs
              # subPath: srv
          env:
          - name: PGID
            value: "0"
          - name: PUID
            value: "0"
      volumes:
        - name: filebrowser-volume-nfs
          persistentVolumeClaim:
            claimName: nfs-pvc-worker-1
