apiVersion: v1
kind: Service
metadata:
  name: livebook-service
  labels:
    app: livebook
spec:
  selector:
    app: livebook
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: livebook-1
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: livebook-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: livebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livebook
  template:
    metadata:
      labels:
        app: livebook
    spec:
      containers:
        - name: livebook
          image: ghcr.io/livebook-dev/livebook
          ports:
            - containerPort: 8080
              name: livebook-1
              protocol: TCP
            - containerPort: 8081
              name: livebook-2
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: livebook-volume-nfs
              subPath: config/livebook/data
          env:
          - name: PGID
            value: "1000"
          - name: PUID
            value: "1000"
          - name: LIVEBOOK_PASSWORD
            value: "securesecret"
      volumes:
        - name: livebook-volume-nfs
          persistentVolumeClaim:
            claimName: nfs-pvc-worker-1
