apiVersion: v1
kind: Service
metadata:
  name: morphos-service
  labels:
    app: morphos
spec:
  selector:
    app: morphos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: morphos-deployment
  labels:
    app: morphos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: morphos
  template:
    metadata:
      labels:
        app: morphos
    spec:
      containers:
        - name: morphos
          image: ghcr.io/danvergara/morphos-server:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: morphos-storage
              mountPath: /tmp
              subPath: home/morphos/tmp
      volumes:
        - name: morphos-storage
          persistentVolumeClaim:
            # claimName: bob-nfs-pvc
            claimName: nfs-pvc-worker-1
