apiVersion: v1
kind: Service
metadata:
  name: openbooks-service
  labels:
    app: openbooks
spec:
  selector:
    app: openbooks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openbooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openbooks
  template:
    metadata:
      labels:
        app: openbooks
    spec:
      containers:
        - name: openbooks
          image: evanbuss/openbooks:latest
          command: ["./openbooks"]
          args: ["server", "--dir", "/books", "--port", "80", "--name", "thebook"]
          ports:
            - containerPort: 80
              name: openbooks-1
              protocol: TCP
          volumeMounts:
            - mountPath: /books
              name: openbooks-volume-nfs
              subPath: home/books

      volumes:
        - name: openbooks-volume-nfs
          persistentVolumeClaim:
            # claimName: bob-nfs-pvc
            claimName: nfs-pvc-worker-1
