apiVersion: v1
kind: Service
metadata:
  name: pdf-service
  labels:
    app: pdf
spec:
  selector:
    app: pdf
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-deployment
  labels:
    app: pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf
  template:
    metadata:
      labels:
        app: pdf
    spec:
      containers:
        - name: pdf
          image: frooodle/s-pdf:latest
          env:
          - name: SECURITY_ENABLE_LOGIN
            value: "true"
          - name: DOCKER_ENABLE_SECURITY 
            value: "true"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /configs
              name: pdf-volume-nfs
              subPath: config/pdf/configs
      volumes:
        - name: pdf-volume-nfs
          persistentVolumeClaim:
            claimName: bob-nfs-pvc
