apiVersion: v1
kind: Service
metadata:
  name: photoprism-service
  labels:
    app: photoprism
spec:
  selector:
    app: photoprism
  ports:
    - protocol: TCP
      port: 2342
      targetPort: 2342
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoprism
  template:
    metadata:
      labels:
        app: photoprism
    spec:
      containers:
        - name: photoprism
          image: photoprism/photoprism:latest
          ports:
            - containerPort: 2342
          volumeMounts:
            - mountPath: /photoprism/storage
              name: photoprism-volume-nfs
              subPath: config/photoprism/storage
            - mountPath: /originals
              name: photoprism-volume-nfs
              subPath: config/photoprism/originals
          env:
          - name: PGID
            value: "1000"
          - name: PUID
            value: "1000"
          - name: TZ
            value: "Etc/UTC"
          - name: PHOTOPRISM_UPLOAD_NSFW
            value: "true"
          - name: PHOTOPRISM_ADMIN_PASSWORD
            value: "insecure"
      volumes:
        - name: photoprism-volume-nfs
          persistentVolumeClaim:
            claimName: nfs-pvc-worker-1
