apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-service
  labels:
    app: vaultwarden
spec:
  selector:
    app: vaultwarden
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          # securityContext:
          #   runAsUser: 0
          #   runAsGroup: 0
          ports:
            - containerPort: 80
              name: vaultwarden-1
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: vaultwarden-volume-nfs
              subPath: config/vaultwarden/data
      volumes:
        - name: vaultwarden-volume-nfs
          persistentVolumeClaim:
            claimName: bob-nfs-pvc
