apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  labels:
    app: sonarr
spec:
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 8989 
      targetPort: 8989
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:latest
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 8989
              name: sonarr-1
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: sonarr-volume-nfs
              subPath: config/sonarr/config
            
            - mountPath: /tv
              name: sonarr-volume-nfs
              subPath: home/sonarr/tv
            - mountPath: /downloads
              name: sonarr-volume-nfs
              subPath: home/sonarr/downloads

      volumes:
        - name: sonarr-volume-nfs
          persistentVolumeClaim:
            claimName: bob-nfs-pvc
