apiVersion: v1
kind: Service
metadata:
  name: filebrowser-service
  labels:
    app: filebrowser
spec:
  selector:
    app: filebrowser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
data:
  # /config # settings.json
  settings.json: |
    {
      "port": 80,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/database/filebrowser.db",
      "root": "/"
    }
kind: ConfigMap
metadata:
  labels:
    app: filebrowser-service
  name: filebrowser-config-file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:s6
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /database
              name: filebrowser-volume
              subPath: database
            # - mountPath: /config # settings.json
            #   name: filebrowser-volume
            #   subPath: config
            - mountPath: /config/settings.json
              name: filebrowser-config
              subPath: settings.json
            - mountPath: /srv
              name: filebrowser-volume
              subPath: srv

            - mountPath: /config # jelly
              name: filebrowser-volume
              subPath: config
            - mountPath: /media # jelly
              name: filebrowser-volume
              subPath: media

            - mountPath: /exadir # exa
              name: filebrowser-volume
              subPath: exadir

            - mountPath: /memos # memos
              name: filebrowser-volume
              subPath: memos

            - mountPath: /data1 # syncting
              name: filebrowser-volume
              subPath: data1
            - mountPath: /data2 # syncting
              name: filebrowser-volume
              subPath: data2
            
      volumes:
        - name: filebrowser-volume
          persistentVolumeClaim:
            claimName: main-pvc
        - configMap:
            name: filebrowser-config-file
          name: filebrowser-config

