apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: listmonk
  name: listmonk
  namespace: listmonk
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: listmonk
---
