apiVersion: v1
kind: Namespace
metadata:
  name: code
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: code
  labels:
    app: postgres
data:
  POSTGRESQL_USERNAME: sonar_user
  POSTGRESQL_DATABASE: sonar_db
  POSTGRESQL_PASSWORD: S0N4RQUB3
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: code
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: code
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 2000 
      containers:
      - name: postgress
        image: bitnami/postgresql
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        envFrom:
        - configMapRef:
            name: postgres
        volumeMounts:
        - name: postgres
          mountPath: /bitnami/postgresql
          subPath: config/postgresql
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: bob-nfs-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-config
  namespace: code
  labels:
    app: sonar
data:
  SONARQUBE_DATABASE_USER: "sonar_user"
  SONARQUBE_DATABASE_PASSWORD: "S0N4RQUB3"
  SONARQUBE_DATABASE_HOST: "postgres"
  SONARQUBE_DATABASE_NAME: "sonar_db"
  JAVA_OPTS: "-Duser.timezone=Asia/Jakarta -Xmx2048m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
  namespace: code
  labels:
    app: sonar
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      initContainers:
      - name: init
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
      containers:
      - name: sonarqube
        image: bitnami/sonarqube:10.4.0
        resources:
          requests:
            memory: "1Gi"
            # cpu: "250m"
          limits:
            memory: "4Gi"
            # cpu: "500m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: sonar-config
        volumeMounts:
        - name: app-pvc
          mountPath: "/opt/sonarqube/data/"
          subPath: config/sonarqube/data
        - name: app-pvc
          mountPath: "/opt/sonarqube/extensions/"
          subPath: config/sonarqube/extensions
      volumes:
      - name: app-pvc
        persistentVolumeClaim:
          claimName: bob-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-svc
  namespace: code
  labels:
    app: sonar
spec:
  ports:
  - port: 9000
    targetPort: 9000
    name: sonar
  selector:
    app: sonar
---
