apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-pvc
  namespace: default
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
