# https://docs.cilium.io/en/stable/network/lb-ipam/
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "pool-cilium-l2"
spec:
  blocks:
    - start: "192.168.1.180"
      stop: "192.168.1.190"
  serviceSelector:
    matchLabels:
      cilium: l2
---
# https://docs.cilium.io/en/latest/network/l2-announcements/
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: "policy-pool-cilium-l2"
spec:
  externalIPs: true
  loadBalancerIPs: true
  interfaces:
    - eth0
    # - ^eth[0-9]+
  serviceSelector:
    matchLabels:
      cilium: l2
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
