apiVersion: v1
kind: Service
metadata:
  name: exatorrent2-service
  labels:
    app: exatorrent2
spec:
  selector:
    app: exatorrent2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exatorrent2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exatorrent2
  template:
    metadata:
      labels:
        app: exatorrent2
    spec:
      containers:
        - name: exatorrent2
          image: ghcr.io/varbhat/exatorrent:latest
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 5000
              name: exatorrent
              protocol: TCP
            - containerPort: 42069
              name: exatorrent2
              protocol: TCP
              # this create /exa/exadir with link srv ?
              # should be correct?
          volumeMounts:
            - mountPath: /exa
              name: exatorrent2-volume
              subPath: exa
            - mountPath: /srv
              name: exatorrent2-volume
              subPath: srv
      volumes:
        - name: exatorrent2-volume
          persistentVolumeClaim:
            claimName: main2-pvc
