apiVersion: v1
kind: Service
metadata:
  name: filebrowser2-service
  labels:
    app: filebrowser2
spec:
  selector:
    app: filebrowser2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser2
  template:
    metadata:
      labels:
        app: filebrowser2
    spec:
      containers:
        - name: filebrowser2
          image: filebrowser/filebrowser:s6
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /database
              name: filebrowser2-volume
              subPath: database
            - mountPath: /config # settings.json
              name: filebrowser2-volume
              subPath: config
            - mountPath: /srv
              name: filebrowser2-volume
              subPath: srv

            - mountPath: /exadir # exa
              name: filebrowser2-volume
              subPath: exadir

            - mountPath: /memos # memos
              name: filebrowser2-volume
              subPath: memos
            
      volumes:
        - name: filebrowser2-volume
          persistentVolumeClaim:
            claimName: main2-pvc
