apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: main2-pvc
 namespace: default
spec:
 storageClassName: rook-cephfs
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 900Gi
---
